<?php
////////////////////////
// Listes des options //
////////////////////////

$ages = array(
  '',
  'Tout',
  '10+',
  '12+',
  '16+',
  '18+'
);

$countries = array(
  '',
  'Argentina',
  'Australia',
  'Bahamas',
  'Belgium',
  'Brazil',
  'Bulgaria',
  'Canada',
  'Chile',
  'China',
  'Czech Republic',
  'Denmark',
  'Finland',
  'France',
  'Germany',
  'Hong Kong',
  'Hungary',
  'India',
  'Indonesia',
  'Ireland',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Luxembourg',
  'Malaysia',
  'Mauritius',
  'Mexico',
  'Netherlands',
  'New Zealand',
  'Norway',
  'Poland',
  'Puerto Rico',
  'Russia',
  'Singapore',
  'South Africa',
  'South Korea',
  'Spain',
  'Sweden',
  'Switzerland',
  'Thailand',
  'Tunisia',
  'Turkey',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States of America'
);

$genres = array(
  'Action',
  'Action / Animation',
  'Action / Animation / Aventure',
  'Action / Animation / Comédie / Familial',
  'Action / Animation / Familial',
  'Action / Animation / Fantastique',
  'Action / Arts Martiaux / Drame / Histoire',
  'Action / Aventure',
  'Action / Aventure / Animation',
  'Action / Aventure / Animation / Comédie / Familial',
  'Action / Aventure / Animation / Comédie / Familial / Fantastique / Science-Fiction',
  'Action / Aventure / Animation / Comédie / Familial / Science-Fiction',
  'Action / Aventure / Animation / Comédie / Familial / Science-Fiction / Fantastique',
  'Action / Aventure / Animation / Drame / Fantastique / Science-Fiction',
  'Action / Aventure / Animation / Familial',
  'Action / Aventure / Animation / Familial / Fantastique / Comédie',
  'Action / Aventure / Animation / Fantastique / Science-Fiction',
  'Action / Aventure / Animation / Horreur / Mystère / Science-Fiction',
  'Action / Aventure / Animation / Science-Fiction / Comédie',
  'Action / Aventure / Animation / Science-Fiction / Thriller',
  'Action / Aventure / Comédie',
  'Action / Aventure / Comédie / Crime / Drame / Thriller',
  'Action / Aventure / Comédie / Crime / Mystère / Thriller',
  'Action / Aventure / Comédie / Crime / Thriller',
  'Action / Aventure / Comédie / Familial / Fantastique / Science-Fiction',
  'Action / Aventure / Comédie / Fantastique',
  'Action / Aventure / Comédie / Fantastique / Science-Fiction / Thriller',
  'Action / Aventure / Comédie / Romance',
  'Action / Aventure / Comédie / Science-Fiction',
  'Action / Aventure / Comédie / Science-Fiction / Western',
  'Action / Aventure / Crime',
  'Action / Aventure / Crime / Drame / Thriller',
  'Action / Aventure / Crime / Mystère',
  'Action / Aventure / Crime / Romance / Thriller',
  'Action / Aventure / Crime / Thriller',
  'Action / Aventure / Drame',
  'Action / Aventure / Drame / Mystère',
  'Action / Aventure / Drame / Mystère / Science-Fiction / Thriller',
  'Action / Aventure / Drame / Romance',
  'Action / Aventure / Drame / Thriller / Guerre',
  'Action / Aventure / Drame / Thriller / Western',
  'Action / Aventure / Familial',
  'Action / Aventure / Familial / Fantastique',
  'Action / Aventure / Familial / Fantastique / Science-Fiction',
  'Action / Aventure / Fantastique',
  'Action / Aventure / Fantastique / Familial',
  'Action / Aventure / Fantastique / Science-Fiction',
  'Action / Aventure / Histoire',
  'Action / Aventure / Histoire / Romance / Drame',
  'Action / Aventure / Horreur / Science-Fiction',
  'Action / Aventure / Mystère / Science-Fiction / Thriller',
  'Action / Aventure / Romance / Science-Fiction / Thriller',
  'Action / Aventure / Science-Fiction',
  'Action / Aventure / Science-Fiction / Drame',
  'Action / Aventure / Science-Fiction / Fantastique',
  'Action / Aventure / Science-Fiction / Thriller',
  'Action / Aventure / Thriller',
  'Action / Aventure / Thriller / Crime',
  'Action / Aventure / Thriller / Guerre',
  'Action / Aventure / Thriller / Science-Fiction',
  'Action / Comédie',
  'Action / Comédie / Crime',
  'Action / Comédie / Crime / Thriller',
  'Action / Comédie / Drame / Thriller',
  'Action / Comédie / Fantastique',
  'Action / Comédie / Fantastique / Science-Fiction / Aventure',
  'Action / Comédie / Guerre',
  'Action / Comédie / Science-Fiction',
  'Action / Comédie / Science-Fiction / Aventure',
  'Action / Comédie / Thriller',
  'Action / Crime',
  'Action / Crime / Comédie',
  'Action / Crime / Comédie / Drame',
  'Action / Crime / Drame',
  'Action / Crime / Drame / Mystère / Science-Fiction / Thriller',
  'Action / Crime / Drame / Mystère / Thriller',
  'Action / Crime / Drame / Thriller',
  'Action / Crime / Fantastique',
  'Action / Crime / Fantastique / Aventure',
  'Action / Crime / Mystère / Science-Fiction / Thriller',
  'Action / Crime / Science-Fiction / Thriller',
  'Action / Crime / Thriller',
  'Action / Drame',
  'Action / Drame / Comédie / Thriller / Science-Fiction',
  'Action / Drame / Crime / Aventure',
  'Action / Drame / Crime / Thriller',
  'Action / Drame / Fantastique',
  'Action / Drame / Guerre',
  'Action / Drame / Histoire / Guerre',
  'Action / Drame / Histoire / Thriller',
  'Action / Drame / Histoire / Thriller / Guerre',
  'Action / Drame / Horreur / Mystère / Thriller',
  'Action / Drame / Horreur / Science-Fiction / Thriller',
  'Action / Drame / Mystère',
  'Action / Drame / Mystère / Thriller',
  'Action / Drame / Science-Fiction',
  'Action / Drame / Thriller',
  'Action / Drame / Thriller / Crime',
  'Action / Drame / Thriller / Guerre',
  'Action / Fantastique',
  'Action / Fantastique / Aventure',
  'Action / Fantastique / Horreur',
  'Action / Fantastique / Science-Fiction',
  'Action / Fantastique / Science-Fiction / Aventure',
  'Action / Fantastique / Thriller',
  'Action / Guerre / Drame / Romance / Thriller',
  'Action / Histoire / Guerre',
  'Action / Histoire / Thriller',
  'Action / Horreur',
  'Action / Horreur / Science-Fiction',
  'Action / Horreur / Thriller',
  'Action / Mystère / Science-Fiction / Thriller',
  'Action / Mystère / Science-Fiction / Thriller / Aventure / Fantastique',
  'Action / Mystère / Thriller',
  'Action / Romance / Guerre',
  'Action / Science-Fiction',
  'Action / Science-Fiction / Aventure',
  'Action / Science-Fiction / Aventure / Fantastique',
  'Action / Science-Fiction / Aventure / Thriller',
  'Action / Science-Fiction / Comédie / Familial',
  'Action / Science-Fiction / Drame',
  'Action / Science-Fiction / Horreur / Aventure',
  'Action / Science-Fiction / Thriller',
  'Action / Science-Fiction / Thriller / Aventure',
  'Action / Science-Fiction / Thriller / Horreur',
  'Action / Science-Fiction / Thriller / Mystère',
  'Action / Thriller',
  'Action / Thriller / Aventure',
  'Action / Thriller / Aventure / Crime',
  'Action / Thriller / Crime',
  'Action / Thriller / Crime / Aventure',
  'Action / Thriller / Crime / Drame',
  'Action / Thriller / Crime / Romance',
  'Action / Thriller / Drame',
  'Action / Thriller / Fantastique',
  'Action / Thriller / Guerre',
  'Action / Thriller / Guerre / Histoire',
  'Action / Thriller / Horreur',
  'Action / Thriller / Mystère',
  'Action / Thriller / Romance',
  'Action / Thriller / Science-Fiction',
  'Action / Thriller / Science-Fiction / Aventure',
  'Action / Thriller / Science-Fiction / Horreur',
  'Action / Thriller / Science-Fiction / Mystère',
  'Action / Thriller / Science-Fiction / Mystère / Aventure',
  'Action / Western',
  'Action / Western / Science-Fiction / Fantastique / Horreur',
  'Animation',
  'Animation / Action / Aventure / Comédie',
  'Animation / Action / Aventure / Familial',
  'Animation / Action / Aventure / Familial / Comédie',
  'Animation / Action / Aventure / Familial / Fantastique',
  'Animation / Action / Aventure / Fantastique / Familial / Drame',
  'Animation / Action / Comédie / Familial',
  'Animation / Action / Comédie / Familial / Science-Fiction',
  'Animation / Action / Familial',
  'Animation / Action / Familial / Science-Fiction',
  'Animation / Action / Science-Fiction / Familial / Aventure',
  'Animation / Aventure',
  'Animation / Aventure / Comédie',
  'Animation / Aventure / Comédie / Familial',
  'Animation / Aventure / Comédie / Familial / Action / Fantastique',
  'Animation / Aventure / Comédie / Familial / Fantastique',
  'Animation / Aventure / Comédie / Familial / Science-Fiction',
  'Animation / Aventure / Comédie / Fantastique / Action / Familial',
  'Animation / Aventure / Drame / Fantastique',
  'Animation / Aventure / Familial',
  'Animation / Aventure / Familial / Comédie',
  'Animation / Aventure / Familial / Fantastique',
  'Animation / Aventure / Familial / Histoire / Guerre',
  'Animation / Aventure / Fantastique',
  'Animation / Aventure / Fantastique / Familial',
  'Animation / Comédie',
  'Animation / Comédie / Action / Aventure / Familial',
  'Animation / Comédie / Aventure',
  'Animation / Comédie / Aventure / Familial',
  'Animation / Comédie / Aventure / Familial / Science-Fiction',
  'Animation / Comédie / Aventure / Fantastique / Familial',
  'Animation / Comédie / Drame / Familial',
  'Animation / Comédie / Drame / Familial / Musique',
  'Animation / Comédie / Drame / Musique / Fantastique',
  'Animation / Comédie / Drame / Romance',
  'Animation / Comédie / Familial',
  'Animation / Comédie / Familial / Action',
  'Animation / Comédie / Familial / Aventure',
  'Animation / Comédie / Familial / Aventure / Fantastique',
  'Animation / Comédie / Familial / Crime / Mystère',
  'Animation / Comédie / Familial / Fantastique',
  'Animation / Comédie / Familial / Musique',
  'Animation / Comédie / Familial / Science-Fiction',
  'Animation / Comédie / Fantastique',
  'Animation / Comédie / Musique',
  'Animation / Drame',
  'Animation / Drame / Familial',
  'Animation / Drame / Familial / Aventure',
  'Animation / Drame / Familial / Fantastique',
  'Animation / Drame / Guerre / Familial',
  'Animation / Drame / Mystère',
  'Animation / Drame / Mystère / Crime / Fantastique / Science-Fiction',
  'Animation / Familial',
  'Animation / Familial / Action',
  'Animation / Familial / Aventure',
  'Animation / Familial / Aventure / Comédie',
  'Animation / Familial / Aventure / Comédie / Fantastique',
  'Animation / Familial / Aventure / Comédie / Guerre',
  'Animation / Familial / Aventure / Comédie / Science-Fiction',
  'Animation / Familial / Aventure / Drame / Fantastique',
  'Animation / Familial / Aventure / Fantastique',
  'Animation / Familial / Aventure / Fantastique / Comédie',
  'Animation / Familial / Aventure / Science-Fiction',
  'Animation / Familial / Comédie',
  'Animation / Familial / Comédie / Aventure',
  'Animation / Familial / Comédie / Aventure / Fantastique / Romance',
  'Animation / Familial / Comédie / Fantastique',
  'Animation / Familial / Comédie / Fantastique / Aventure / Musique',
  'Animation / Familial / Comédie / Musique',
  'Animation / Familial / Fantastique',
  'Animation / Familial / Fantastique / Aventure',
  'Animation / Familial / Fantastique / Aventure / Comédie',
  'Animation / Familial / Fantastique / Aventure / Comédie / Romance',
  'Animation / Familial / Histoire / Aventure',
  'Animation / Familial / Musique',
  'Animation / Familial / Science-Fiction',
  'Animation / Fantastique',
  'Animation / Fantastique / Aventure / Action / Familial',
  'Animation / Fantastique / Comédie',
  'Animation / Fantastique / Familial',
  'Animation / Fantastique / Familial / Aventure',
  'Animation / Horreur / Action / Science-Fiction',
  'Animation / Musique / Familial / Aventure / Fantastique',
  'Animation / Romance / Aventure / Drame / Fantastique',
  'Animation / Romance / Familial / Fantastique',
  'Animation / Science-Fiction',
  'Animation / Science-Fiction / Action',
  'Animation / Science-Fiction / Familial',
  'Animation / Science-Fiction / Thriller',
  'Anime',
  'Arts Martiaux',
  'Aventure',
  'Aventure / Action',
  'Aventure / Action / Animation',
  'Aventure / Action / Comédie / Science-Fiction / Familial',
  'Aventure / Action / Comédie / Thriller / Crime',
  'Aventure / Action / Crime / Mystère',
  'Aventure / Action / Fantastique',
  'Aventure / Action / Fantastique / Comédie',
  'Aventure / Action / Fantastique / Mystère / Thriller',
  'Aventure / Action / Science-Fiction',
  'Aventure / Action / Science-Fiction / Thriller',
  'Aventure / Action / Thriller',
  'Aventure / Action / Thriller / Crime',
  'Aventure / Action / Thriller / Crime / Mystère',
  'Aventure / Action / Thriller / Science-Fiction',
  'Aventure / Action / Western',
  'Aventure / Animation / Comédie',
  'Aventure / Animation / Comédie / Drame',
  'Aventure / Animation / Comédie / Familial',
  'Aventure / Animation / Comédie / Familial / Fantastique',
  'Aventure / Animation / Comédie / Familial / Fantastique / Romance',
  'Aventure / Animation / Comédie / Familial / Musique',
  'Aventure / Animation / Comédie / Familial / Science-Fiction',
  'Aventure / Animation / Comédie / Fantastique',
  'Aventure / Animation / Comédie / Fantastique / Familial',
  'Aventure / Animation / Comédie / Science-Fiction / Familial',
  'Aventure / Animation / Drame / Familial',
  'Aventure / Animation / Drame / Familial / Musique / Comédie',
  'Aventure / Animation / Familial',
  'Aventure / Animation / Familial / Comédie',
  'Aventure / Animation / Familial / Comédie / Fantastique',
  'Aventure / Animation / Familial / Drame / Action',
  'Aventure / Animation / Familial / Fantastique',
  'Aventure / Animation / Familial / Fantastique / Science-Fiction',
  'Aventure / Animation / Familial / Musique',
  'Aventure / Animation / Familial / Romance',
  'Aventure / Animation / Mystère',
  'Aventure / Animation / Romance / Familial',
  'Aventure / Comédie',
  'Aventure / Comédie / Animation',
  'Aventure / Comédie / Animation / Familial',
  'Aventure / Comédie / Drame',
  'Aventure / Comédie / Familial',
  'Aventure / Comédie / Familial / Fantastique',
  'Aventure / Comédie / Familial / Science-Fiction',
  'Aventure / Comédie / Familial / Science-Fiction / Action',
  'Aventure / Comédie / Fantastique',
  'Aventure / Comédie / Fantastique / Familial / Horreur',
  'Aventure / Comédie / Science-Fiction',
  'Aventure / Comédie / Science-Fiction / Familial',
  'Aventure / Drame',
  'Aventure / Drame / Action',
  'Aventure / Drame / Action / Romance',
  'Aventure / Drame / Action / Romance / Familial',
  'Aventure / Drame / Comédie',
  'Aventure / Drame / Familial',
  'Aventure / Drame / Fantastique',
  'Aventure / Drame / Histoire / Thriller / Guerre',
  'Aventure / Drame / Romance',
  'Aventure / Drame / Romance / Science-Fiction',
  'Aventure / Drame / Science-Fiction',
  'Aventure / Drame / Western',
  'Aventure / Familial',
  'Aventure / Familial / Animation / Action / Comédie',
  'Aventure / Familial / Animation / Comédie / Science-Fiction / Fantastique',
  'Aventure / Familial / Fantastique',
  'Aventure / Familial / Fantastique / Animation',
  'Aventure / Fantastique',
  'Aventure / Fantastique / Action',
  'Aventure / Fantastique / Action / Romance',
  'Aventure / Fantastique / Action / Thriller / Science-Fiction',
  'Aventure / Fantastique / Animation',
  'Aventure / Fantastique / Animation / Action / Thriller / Science-Fiction',
  'Aventure / Fantastique / Animation / Comédie / Action / Familial',
  'Aventure / Fantastique / Animation / Comédie / Familial / Musique',
  'Aventure / Fantastique / Animation / Crime',
  'Aventure / Fantastique / Animation / Familial',
  'Aventure / Fantastique / Comédie / Familial',
  'Aventure / Fantastique / Drame',
  'Aventure / Fantastique / Drame / Romance',
  'Aventure / Fantastique / Familial',
  'Aventure / Fantastique / Familial / Mystère',
  'Aventure / Fantastique / Romance',
  'Aventure / Fantastique / Romance / Comédie / Familial',
  'Aventure / Fantastique / Science-Fiction',
  'Aventure / Fantastique / Science-Fiction / Action',
  'Aventure / Histoire / Action / Science-Fiction / Comédie / Fantastique / Histoire',
  'Aventure / Histoire / Romance',
  'Aventure / Horreur / Action / Histoire',
  'Aventure / Horreur / Comédie',
  'Aventure / Mystère / Romance',
  'Aventure / Romance / Histoire',
  'Aventure / Science-Fiction',
  'Aventure / Science-Fiction / Action',
  'Aventure / Science-Fiction / Familial / Fantastique',
  'Aventure / Science-Fiction / Fantastique',
  'Aventure / Science-Fiction / Fantastique / Action',
  'Comédie',
  'Comédie / Action',
  'Comédie / Action / Crime',
  'Comédie / Action / Drame / Thriller / Fantastique',
  'Comédie / Animation / Action',
  'Comédie / Animation / Aventure',
  'Comédie / Animation / Aventure / Familial',
  'Comédie / Animation / Aventure / Familial / Fantastique',
  'Comédie / Animation / Aventure / Familial / Science-Fiction',
  'Comédie / Animation / Familial',
  'Comédie / Animation / Familial / Aventure',
  'Comédie / Animation / Fantastique',
  'Comédie / Aventure / Familial',
  'Comédie / Aventure / Familial / Animation',
  'Comédie / Aventure / Familial / Fantastique / Animation',
  'Comédie / Aventure / Fantastique / Animation / Familial',
  'Comédie / Crime',
  'Comédie / Crime / Aventure / Fantastique',
  'Comédie / Crime / Drame / Horreur',
  'Comédie / Drame',
  'Comédie / Drame / Musique',
  'Comédie / Drame / Romance',
  'Comédie / Drame / Romance / Fantastique / Aventure',
  'Comédie / Drame / Science-Fiction',
  'Comédie / Drame / Western',
  'Comédie / Familial',
  'Comédie / Familial / Animation',
  'Comédie / Familial / Animation / Aventure',
  'Comédie / Familial / Animation / Fantastique / Musique',
  'Comédie / Familial / Aventure / Crime',
  'Comédie / Familial / Fantastique / Horreur',
  'Comédie / Familial / Fantastique / Romance',
  'Comédie / Fantastique',
  'Comédie / Fantastique / Aventure / Familial',
  'Comédie / Fantastique / Familial / Musique / Animation',
  'Comédie / Fantastique / Science-Fiction',
  'Comédie / Guerre',
  'Comédie / Guerre / Drame',
  'Comédie / Histoire',
  'Comédie / Horreur / Fantastique',
  'Comédie / Horreur / Thriller',
  'Comédie / Musique',
  'Comédie / Musique / Familial / Animation',
  'Comédie / Musique / Familial / Fantastique',
  'Comédie / Musique / Familial / Fantastique / Animation',
  'Comédie / Romance',
  'Comédie / Romance / Crime',
  'Comédie / Romance / Drame',
  'Comédie / Science-Fiction',
  'Court-métrage / Animation',
  'Crime',
  'Crime / Action',
  'Crime / Action / Aventure / Comédie',
  'Crime / Action / Comédie',
  'Crime / Action / Comédie / Aventure',
  'Crime / Action / Mystère / Thriller',
  'Crime / Action / Science-Fiction',
  'Crime / Action / Thriller',
  'Crime / Comédie / Action',
  'Crime / Comédie / Action / Aventure',
  'Crime / Comédie / Action / Thriller',
  'Crime / Drame',
  'Crime / Drame / Histoire',
  'Crime / Drame / Histoire / Thriller',
  'Crime / Drame / Mystère',
  'Crime / Drame / Mystère / Romance / Thriller',
  'Crime / Drame / Mystère / Thriller',
  'Crime / Drame / Mystère / Western',
  'Crime / Drame / Science-Fiction / Thriller',
  'Crime / Drame / Thriller',
  'Crime / Drame / Thriller / Horreur',
  'Crime / Fantastique / Drame',
  'Crime / Histoire',
  'Crime / Horreur / Mystère',
  'Crime / Horreur / Mystère / Thriller',
  'Crime / Mystère',
  'Crime / Mystère / Drame',
  'Crime / Mystère / Thriller',
  'Crime / Thriller',
  'Crime / Thriller / Aventure',
  'Crime / Thriller / Drame',
  'Crime / Thriller / Drame / Comédie',
  'Crime / Thriller / Horreur',
  'Crime / Thriller / Mystère / Drame',
  'Documentaire',
  'Documentaire / Familial',
  'Drame',
  'Drame / Action',
  'Drame / Action / Aventure / Histoire / Guerre',
  'Drame / Action / Crime / Thriller',
  'Drame / Action / Guerre / Fantastique',
  'Drame / Action / Science-Fiction',
  'Drame / Action / Thriller',
  'Drame / Action / Thriller / Crime',
  'Drame / Action / Thriller / Guerre',
  'Drame / Action / Thriller / Science-Fiction',
  'Drame / Animation / Aventure',
  'Drame / Animation / Familial / Comédie',
  'Drame / Animation / Familial / Comédie / Fantastique',
  'Drame / Aventure',
  'Drame / Aventure / Familial',
  'Drame / Aventure / Science-Fiction',
  'Drame / Comédie',
  'Drame / Comédie / Crime / Thriller',
  'Drame / Comédie / Histoire / Romance',
  'Drame / Comédie / Romance',
  'Drame / Comédie / Thriller',
  'Drame / Crime',
  'Drame / Crime / Thriller',
  'Drame / Familial',
  'Drame / Familial / Animation / Aventure',
  'Drame / Familial / Aventure',
  'Drame / Fantastique',
  'Drame / Fantastique / Horreur',
  'Drame / Fantastique / Horreur / Thriller',
  'Drame / Fantastique / Romance',
  'Drame / Fantastique / Romance / Aventure',
  'Drame / Fantastique / Thriller / Mystère',
  'Drame / Guerre',
  'Drame / Guerre / Action',
  'Drame / Histoire',
  'Drame / Histoire / Action / Thriller',
  'Drame / Histoire / Comédie',
  'Drame / Histoire / Crime',
  'Drame / Histoire / Guerre',
  'Drame / Histoire / Guerre / Action',
  'Drame / Histoire / Romance',
  'Drame / Histoire / Thriller',
  'Drame / Horreur',
  'Drame / Horreur / Action / Thriller / Science-Fiction',
  'Drame / Horreur / Musique / Thriller',
  'Drame / Horreur / Mystère / Thriller',
  'Drame / Horreur / Thriller',
  'Drame / Horreur / Thriller / Science-Fiction',
  'Drame / Musique',
  'Drame / Musique / Romance',
  'Drame / Mystère',
  'Drame / Mystère / Science-Fiction',
  'Drame / Mystère / Science-Fiction / Thriller',
  'Drame / Mystère / Thriller',
  'Drame / Romance',
  'Drame / Romance / Thriller',
  'Drame / Science-Fiction',
  'Drame / Science-Fiction / Animation',
  'Drame / Science-Fiction / Aventure',
  'Drame / Science-Fiction / Guerre',
  'Drame / Science-Fiction / Mystère',
  'Drame / Thriller',
  'Drame / Thriller / Action',
  'Drame / Thriller / Aventure',
  'Drame / Thriller / Crime',
  'Drame / Thriller / Crime / Mystère',
  'Drame / Thriller / Crime / Mystère / Romance',
  'Drame / Thriller / Guerre',
  'Drame / Thriller / Histoire / Guerre',
  'Drame / Thriller / Mystère',
  'Drame / Western',
  'Drame / Western / Crime',
  'Drame / Western / Histoire',
  'Érotique',
  'Familial / Animation',
  'Familial / Animation / Aventure',
  'Familial / Animation / Aventure / Comédie',
  'Familial / Animation / Aventure / Comédie / Fantastique / Action',
  'Familial / Animation / Comédie',
  'Familial / Animation / Comédie / Aventure',
  'Familial / Animation / Comédie / Fantastique',
  'Familial / Animation / Comédie / Mystère / Aventure',
  'Familial / Animation / Fantastique',
  'Familial / Animation / Fantastique / Comédie',
  'Familial / Animation / Fantastique / Comédie / Aventure',
  'Familial / Animation / Romance / Fantastique',
  'Familial / Aventure',
  'Familial / Aventure / Animation',
  'Familial / Aventure / Animation / Action',
  'Familial / Aventure / Animation / Romance',
  'Familial / Comédie / Animation / Aventure',
  'Familial / Fantastique',
  'Familial / Fantastique / Animation',
  'Familial / Fantastique / Animation / Aventure',
  'Familial / Fantastique / Animation / Comédie / Aventure',
  'Familial / Fantastique / Aventure',
  'Familial / Fantastique / Aventure / Animation / Comédie',
  'Familial / Fantastique / Comédie / Animation',
  'Familial / Fantastique / Romance',
  'Familial / Science-Fiction',
  'Familial / Science-Fiction / Fantastique / Aventure',
  'Fantastique',
  'Fantastique / Action',
  'Fantastique / Action / Animation / Comédie / Familial',
  'Fantastique / Action / Aventure',
  'Fantastique / Action / Aventure / Animation',
  'Fantastique / Action / Aventure / Animation / Comédie / Familial',
  'Fantastique / Action / Aventure / Science-Fiction / Thriller',
  'Fantastique / Action / Comédie / Crime',
  'Fantastique / Action / Comédie / Science-Fiction / Familial',
  'Fantastique / Action / Crime',
  'Fantastique / Action / Drame',
  'Fantastique / Action / Horreur',
  'Fantastique / Action / Science-Fiction / Thriller',
  'Fantastique / Action / Thriller',
  'Fantastique / Action / Thriller / Crime / Science-Fiction / Mystère',
  'Fantastique / Animation / Action / Comédie',
  'Fantastique / Animation / Aventure / Comédie / Familial',
  'Fantastique / Animation / Comédie / Crime / Familial',
  'Fantastique / Animation / Comédie / Familial / Aventure',
  'Fantastique / Animation / Comédie / Science-Fiction / Familial',
  'Fantastique / Animation / Drame / Romance / Familial',
  'Fantastique / Animation / Familial',
  'Fantastique / Animation / Familial / Aventure',
  'Fantastique / Animation / Familial / Comédie',
  'Fantastique / Animation / Familial / Mystère',
  'Fantastique / Animation / Familial / Romance',
  'Fantastique / Animation / Musique / Familial',
  'Fantastique / Animation / Romance / Familial',
  'Fantastique / Animation / Science-Fiction / Familial / Action',
  'Fantastique / Aventure / Action / Comédie / Drame',
  'Fantastique / Aventure / Action / Familial / Romance',
  'Fantastique / Aventure / Animation',
  'Fantastique / Aventure / Animation / Comédie / Familial',
  'Fantastique / Aventure / Animation / Comédie / Familial / Musique',
  'Fantastique / Aventure / Animation / Familial',
  'Fantastique / Aventure / Comédie',
  'Fantastique / Aventure / Familial',
  'Fantastique / Aventure / Familial / Animation',
  'Fantastique / Comédie',
  'Fantastique / Comédie / Animation / Science-Fiction / Familial',
  'Fantastique / Comédie / Familial / Romance',
  'Fantastique / Comédie / Science-Fiction',
  'Fantastique / Drame / Crime',
  'Fantastique / Drame / Mystère',
  'Fantastique / Drame / Romance',
  'Fantastique / Drame / Thriller / Romance',
  'Fantastique / Familial / Animation / Aventure',
  'Fantastique / Familial / Aventure',
  'Fantastique / Familial / Aventure / Drame',
  'Fantastique / Familial / Comédie',
  'Fantastique / Familial / Comédie / Animation',
  'Fantastique / Horreur / Action',
  'Fantastique / Horreur / Comédie',
  'Fantastique / Romance',
  'Fantastique / Science-Fiction / Familial / Animation',
  'Fantastique / Thriller / Drame',
  'Guerre',
  'Guerre / Action',
  'Guerre / Action / Drame',
  'Guerre / Action / Thriller / Science-Fiction',
  'Guerre / Comédie',
  'Guerre / Drame',
  'Guerre / Drame / Action',
  'Guerre / Drame / Action / Thriller / Histoire',
  'Guerre / Drame / Histoire',
  'Guerre / Drame / Histoire / Action',
  'Guerre / Histoire / Action / Drame',
  'Histoire / Action',
  'Histoire / Action / Drame / Guerre',
  'Histoire / Animation',
  'Histoire / Aventure / Action',
  'Histoire / Drame',
  'Histoire / Drame / Romance',
  'Histoire / Thriller / Guerre',
  'Horreur',
  'Horreur / Action',
  'Horreur / Action / Drame / Fantastique / Guerre',
  'Horreur / Action / Science-Fiction',
  'Horreur / Action / Thriller',
  'Horreur / Action / Thriller / Science-Fiction',
  'Horreur / Comédie',
  'Horreur / Comédie / Animation / Familial / Fantastique / Aventure / Science-Fiction',
  'Horreur / Comédie / Musique',
  'Horreur / Crime',
  'Horreur / Drame / Fantastique',
  'Horreur / Drame / Mystère / Thriller',
  'Horreur / Fantastique / Animation / Familial',
  'Horreur / Fantastique / Thriller / Familial / Mystère',
  'Horreur / Guerre / Action / Science-Fiction',
  'Horreur / Mystère',
  'Horreur / Mystère / Crime',
  'Horreur / Mystère / Thriller',
  'Horreur / Mystère / Thriller / Drame',
  'Horreur / Romance',
  'Horreur / Science-Fiction / Thriller',
  'Horreur / Thriller',
  'Horreur / Thriller / Crime',
  'Horreur / Thriller / Mystère',
  'Horreur / Thriller / Mystère / Comédie',
  'Musique / Animation / Familial / Fantastique',
  'Musique / Animation / Familial / Fantastique / Aventure',
  'Musique / Aventure / Animation / Action / Comédie',
  'Musique / Aventure / Animation / Familial / Fantastique',
  'Musique / Comédie / Animation',
  'Musique / Comédie / Drame',
  'Musique / Drame',
  'Musique / Familial / Animation',
  'Musique / Familial / Fantastique / Comédie',
  'Mystère',
  'Mystère / Aventure / Drame',
  'Mystère / Aventure / Thriller / Horreur',
  'Mystère / Fantastique / Aventure',
  'Mystère / Fantastique / Science-Fiction',
  'Mystère / Horreur',
  'Mystère / Horreur / Thriller',
  'Mystère / Science-Fiction',
  'Mystère / Science-Fiction / Drame / Aventure / Fantastique / Horreur / Thriller',
  'Mystère / Science-Fiction / Thriller',
  'Mystère / Thriller',
  'Mystère / Thriller / Comédie',
  'Mystère / Thriller / Drame',
  'Mystère / Thriller / Horreur',
  'Mystère / Thriller / Horreur / Science-Fiction',
  'One-man-show / Spectacle',
  'One-woman-show / Spectacle',
  'Péplum',
  'Romance / Animation / Aventure / Comédie / Familial / Fantastique',
  'Romance / Animation / Comédie / Familial / Fantastique / Mystère / Aventure',
  'Romance / Animation / Familial / Aventure',
  'Romance / Animation / Familial / Aventure / Fantastique',
  'Romance / Animation / Familial / Comédie / Aventure',
  'Romance / Comédie',
  'Romance / Comédie / Crime / Fantastique',
  'Romance / Drame',
  'Romance / Drame / Comédie',
  'Romance / Familial / Animation / Fantastique / Musique',
  'Romance / Fantastique / Animation',
  'Romance / Fantastique / Drame / Comédie',
  'Romance / Fantastique / Familial / Drame',
  'Science-Fiction',
  'Science-Fiction / Action',
  'Science-Fiction / Action / Animation',
  'Science-Fiction / Action / Aventure',
  'Science-Fiction / Action / Aventure / Comédie / Familial',
  'Science-Fiction / Action / Aventure / Comédie / Fantastique',
  'Science-Fiction / Action / Aventure / Familial',
  'Science-Fiction / Action / Aventure / Fantastique / Comédie',
  'Science-Fiction / Action / Aventure / Fantastique / Thriller',
  'Science-Fiction / Action / Aventure / Thriller',
  'Science-Fiction / Action / Crime / Drame',
  'Science-Fiction / Action / Crime / Thriller / Drame',
  'Science-Fiction / Action / Drame / Thriller',
  'Science-Fiction / Action / Fantastique',
  'Science-Fiction / Action / Horreur',
  'Science-Fiction / Action / Horreur / Thriller / Aventure / Fantastique',
  'Science-Fiction / Action / Thriller',
  'Science-Fiction / Action / Thriller / Aventure',
  'Science-Fiction / Animation',
  'Science-Fiction / Animation / Action / Crime',
  'Science-Fiction / Animation / Action / Familial / Comédie',
  'Science-Fiction / Animation / Comédie / Familial',
  'Science-Fiction / Aventure',
  'Science-Fiction / Aventure / Action',
  'Science-Fiction / Aventure / Action / Comédie / Familial',
  'Science-Fiction / Aventure / Familial / Fantastique',
  'Science-Fiction / Aventure / Fantastique',
  'Science-Fiction / Aventure / Mystère',
  'Science-Fiction / Aventure / Thriller',
  'Science-Fiction / Comédie / Action / Fantastique',
  'Science-Fiction / Drame / Thriller',
  'Science-Fiction / Familial / Comédie / Aventure / Animation',
  'Science-Fiction / Fantastique',
  'Science-Fiction / Fantastique / Action',
  'Science-Fiction / Fantastique / Action / Aventure',
  'Science-Fiction / Fantastique / Aventure',
  'Science-Fiction / Fantastique / Aventure / Familial',
  'Science-Fiction / Horreur / Action',
  'Science-Fiction / Horreur / Action / Thriller',
  'Science-Fiction / Horreur / Thriller',
  'Science-Fiction / Mystère / Aventure',
  'Science-Fiction / Thriller',
  'Science-Fiction / Thriller / Action / Aventure',
  'Science-Fiction / Thriller / Drame',
  'Science-Fiction / Thriller / Drame / Crime',
  'Science-Fiction / Thriller / Horreur',
  'Science-Fiction / Thriller / Mystère',
  'Spectacle',
  'Thriller',
  'Thriller / Action',
  'Thriller / Action / Aventure',
  'Thriller / Action / Crime',
  'Thriller / Action / Drame',
  'Thriller / Action / Drame / Musique / Romance',
  'Thriller / Action / Drame / Romance',
  'Thriller / Action / Drame / Science-Fiction',
  'Thriller / Action / Science-Fiction / Romance',
  'Thriller / Animation / Action / Science-Fiction / Aventure / Fantastique',
  'Thriller / Comédie / Action / Drame',
  'Thriller / Comédie / Drame / Romance / Science-Fiction',
  'Thriller / Crime',
  'Thriller / Crime / Drame',
  'Thriller / Crime / Drame / Histoire',
  'Thriller / Crime / Horreur',
  'Thriller / Crime / Mystère / Comédie / Drame',
  'Thriller / Crime / Mystère / Drame',
  'Thriller / Crime / Romance',
  'Thriller / Drame',
  'Thriller / Drame / Comédie',
  'Thriller / Drame / Crime',
  'Thriller / Drame / Histoire',
  'Thriller / Drame / Mystère',
  'Thriller / Fantastique',
  'Thriller / Horreur',
  'Thriller / Horreur / Drame',
  'Thriller / Horreur / Drame / Fantastique',
  'Thriller / Horreur / Mystère',
  'Thriller / Mystère',
  'Thriller / Mystère / Crime',
  'Thriller / Mystère / Drame / Fantastique / Science-Fiction',
  'Thriller / Mystère / Drame / Horreur',
  'Thriller / Mystère / Horreur',
  'Thriller / Mystère / Science-Fiction',
  'Thriller / Science-Fiction',
  'Thriller / Science-Fiction / Action',
  'Thriller / Science-Fiction / Drame / Mystère',
  'Thriller / Science-Fiction / Horreur',
  'Thriller / Science-Fiction / Mystère',
  'Western',
  'Western / Drame',
  'Western / Drame / Aventure / Thriller'
);
